### ISSUE TITLE
Support PNG and JPEG figures in reports

### ISSUE THREAD

**Issue by tsalo** [nipreps/nireports#124]
### What would you like to see added in this software?

With 23.2.1, it doesn't look like PNG figures are collected by Nireports, even when I specify the extension field as `.png` or `png`. If possible, it would be great to support these figures, as QSIRecon has some figures that it can't save as SVGs.

### Do you have any interest in helping implement the feature?

Yes

**Comment by effigies** [comment]
Agreed. nireports should be general, even if most nipreps exclusively use HTML and SVG.

**Comment by mattcieslak** [comment]
Thank you @tsalo for putting this together! This would be a big deal for dMRI reports because a lot of them are rasterized 3d renderings from FURY. Instead of embedding them in svgs, it would be very convenient just to send them to the reports directly.

**Comment by tsalo** [comment]
I think we could close this, but one thing @mattcieslak and I realized after I merged #126 is that I forgot about GIFs.
