### ISSUE TITLE
Identify the modules from niworkflows that must be ported

### ISSUE THREAD

**Issue by oesteban** [nipreps/nireports#3]
- dont forget the Notebook extension/wrapper https://github.com/nipreps/niworkflows/blob/master/niworkflows/viz/notebook.py

**Comment by WMDA** [comment]
@eilidhmacnicol @celprov I am also happy to help work on this issue and/or any of issues #2 , #3, #5 . The more I have been researching about the zip button idea the more it seems like a cool secondary feature that might make sense to do after we have got a basic outline of the nireports  package. I dunno if that makes sense to you guys?

**Comment by celprov** [comment]
@WMDA sure happy to collaborate on those issues :)
