### ISSUE TITLE
Set up a MAINTAINERS team & add GOVERNANCE files (``.maint/*`` et al.)

### ISSUE THREAD

**Issue by oesteban** [nipreps/nireports#47]
### What would you like to see added in this software?

@esavary, please address this issue (adding the GOVERNANCE files where they belong) and coordinate a maintainers team.

@celprov, if I'm right, you wanted to volunteer as a maintainer?

This project may potentially be of interest to @Shotgunosine (as it would be the right place to integrate, e.g., group-aggregated reports for fmriprep)

Who else wants to join? cc/ @nipreps/fmriprep-contributors 

### Do you have any interest in helping implement the feature?

Yes

**Comment by celprov** [comment]
@oesteban yes I'm volunteering to become a maintainer of nireports.
