### ISSUE TITLE
Weird aspect ratio of some mosaic plots

### ISSUE THREAD

**Issue by oesteban** [nipreps/nireports#53]
### What happened?

https://output.circle-artifacts.com/output/job/0d458179-b043-4f5c-ae2e-25bb26f98f15/artifacts/0/tmp/t1w/derivatives/sub-51187_T1w.html

### What command did you use?

```shell
mriqc
```

### What version of fMRIPrep are you running?

n/a

### How are you running this software?

Local installation ("bare-metal")

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by celprov** [comment]
I have the same problem running MRIQC v.23.0.0rc0 through Docker on the [IXI dataset](https://brain-development.org/ixi-dataset/). All the mosaics are elongated.

![image](https://github.com/nipreps/nireports/assets/77437752/983c8a4d-2535-4979-806f-8af740d0eb64)
![image](https://github.com/nipreps/nireports/assets/77437752/66796abc-cd4e-4e3e-9d04-1809eb2342e5)

**Comment by celprov** [comment]
According to,
> import nibabel as nib
> img = nib.load("filename")
> img.affine

The affines are different for each image.
![image](https://github.com/nipreps/nireports/assets/77437752/6af2e2bf-8633-4e92-89ec-da83639c329a)

**Comment by effigies** [comment]
Which of these images is shown above?

**Comment by oesteban** [comment]
The shape will also be necessary :)

BTW, images are rotated to the closest canonical, so please report

```python
import nibabel as nib
img = nib.as_closest_canonical(nib.load("filename"))
img.affine, img.shape
```

**Comment by celprov** [comment]
The image above comes from sub-113.

img.shape = (150, 256, 256)
img.affine = array([[ 4.58331546e-03, -2.94111557e-02,  1.19939470e+00,
        -8.33061523e+01],
       [-9.36585963e-01,  4.09624688e-02,  7.50960456e-03,
         1.13431572e+02],
       [ 4.11258750e-02,  9.36142504e-01,  3.73532586e-02,
        -1.23132339e+02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

**Comment by oesteban** [comment]
Okay, I believe I know what's going on. Here the aspect ratios are calculated (the axial hard-coded 1.0 might be also related):

https://github.com/nipreps/nireports/blob/5c1a8b25257fff27cf35f87fa40eca11683c9786/nireports/reportlets/mosaic.py#L532-L536

However, these would be okay for a full image plotting. However, we are plotting zoomed in the brain mask. The aspect ratio should be calculated only with the bounding box, rather than the full images.

does that make sense?
