### ISSUE TITLE
Set up CI workflow with GitHub actions

### ISSUE THREAD

**Issue by ZviBaratz** [nipreps/nireports#6]
Create basic build and test workflow.

**Comment by mgxd** [comment]
regarding artifacts - i haven't tried it, but https://github.com/actions/upload-artifact looks pretty intuitive

**Comment by eilidhmacnicol** [comment]
@LenFrahm good with me but probably best to liase with @effigies over his work that set up the initial infrastructure (#8) and what he had planned to test the actions he has set up (https://github.com/nipreps/nireports/pull/8#issuecomment-1151401891) to see what else is necessary ahead of time and what will still need doing on Friday

**Comment by effigies** [comment]
Uploading artifacts works, but you can't view them without downloading and unzipping. Circle artifacts are viewable online.

**Comment by oesteban** [comment]
Opened a new issue for Circle - closing this one as the testing workflow seems to be working (and it's a good start)
