### ISSUE TITLE
Initiate documentation building

### ISSUE THREAD

**Issue by oesteban** [nipreps/nireports#7]
- Making sure we embed generated reportlets within the explanations
- Integration of jupyter-books? (cc/ @effigies )

**Comment by ZviBaratz** [comment]
@oesteban Do we mean for the documentation site to be a Jupyter book build? We could also use [sphinx with embedded notebooks](https://docs.readthedocs.io/en/stable/guides/jupyter.html).

**Comment by oesteban** [comment]
I would default to sphinx with embedded notebooks, just mentioned Chris because he mentioned the option of jupyter books.

**Comment by ZviBaratz** [comment]
> Making sure we embed generated reportlets within the explanations

@eilidhmacnicol @oesteban I think it might be best to open a separate issue for creating notebook examples etc., so that this maintains the original scope of documentation initiation.
